version: 0.1
phases:
  install:
    commands:
      - npm --prefix ./be/app install
  build:
    commands:
      - echo run tsc build
      - npm --prefix ./be/app run build
      - aws cloudformation package --template-file be/app/samTemplate.yaml --s3-bucket synclair-artefacts
                                         --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml